/** States & UTs of India (36) — administrative names for filters. */
export const INDIA_STATES_AND_UTS = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export type IndiaState = (typeof INDIA_STATES_AND_UTS)[number];

/**
 * Approximate number of revenue / administrative districts per state & UT.
 * Totals ~766 — aligns with common post-2020 reorganisation figures (rounded).
 * District *names* for non-overridden states are generated as "District {n}" for browsing;
 * swap this module for a UDISE/AICTE-backed API when you wire real master data.
 */
export const DISTRICT_COUNT_BY_STATE: Record<IndiaState, number> = {
  "Andhra Pradesh": 26,
  "Arunachal Pradesh": 26,
  Assam: 35,
  Bihar: 38,
  Chhattisgarh: 33,
  Goa: 2,
  Gujarat: 33,
  Haryana: 22,
  "Himachal Pradesh": 12,
  Jharkhand: 24,
  Karnataka: 31,
  Kerala: 14,
  "Madhya Pradesh": 55,
  Maharashtra: 36,
  Manipur: 16,
  Meghalaya: 12,
  Mizoram: 11,
  Nagaland: 16,
  Odisha: 30,
  Punjab: 23,
  Rajasthan: 50,
  Sikkim: 6,
  "Tamil Nadu": 38,
  Telangana: 33,
  Tripura: 8,
  "Uttar Pradesh": 75,
  Uttarakhand: 13,
  "West Bengal": 23,
  "Andaman and Nicobar Islands": 3,
  Chandigarh: 1,
  "Dadra and Nagar Haveli and Daman and Diu": 3,
  Delhi: 11,
  "Jammu and Kashmir": 20,
  Ladakh: 2,
  Lakshadweep: 1,
  Puducherry: 4,
};

/** Optional real district names (subset) — remainder filled with numbered units. */
const NAMED_DISTRICTS: Partial<Record<IndiaState, readonly string[]>> = {
  Maharashtra: [
    "Mumbai City",
    "Mumbai Suburban",
    "Thane",
    "Palghar",
    "Raigad",
    "Pune",
    "Nashik",
    "Nagpur",
    "Ahmednagar",
    "Solapur",
    "Kolhapur",
    "Sangli",
    "Satara",
    "Ratnagiri",
    "Sindhudurg",
    "Dhule",
    "Jalgaon",
    "Akola",
    "Amravati",
    "Buldhana",
    "Yavatmal",
    "Wardha",
    "Chandrapur",
    "Gadchiroli",
    "Gondia",
    "Bhandara",
    "Washim",
    "Hingoli",
    "Nanded",
    "Latur",
    "Osmanabad",
    "Beed",
    "Parbhani",
    "Jalna",
    "Aurangabad",
    "Nandurbar",
  ],
  Karnataka: [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Ramanagara",
    "Mysuru",
    "Mandya",
    "Hassan",
    "Chikkamagaluru",
    "Shivamogga",
    "Davanagere",
    "Ballari",
    "Raichur",
    "Koppal",
    "Gadag",
    "Dharwad",
    "Belagavi",
    "Bagalkote",
    "Vijayapura",
    "Kalaburagi",
    "Bidar",
    "Yadgir",
    "Kolar",
    "Chikkaballapura",
    "Tumakuru",
    "Chitradurga",
    "Udupi",
    "Dakshina Kannada",
    "Kodagu",
    "Uttara Kannada",
    "Haveri",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Kanchipuram",
    "Tiruvallur",
    "Vellore",
    "Ranipet",
    "Tirupathur",
    "Krishnagiri",
    "Dharmapuri",
    "Salem",
    "Namakkal",
    "Erode",
    "Tiruppur",
    "Coimbatore",
    "Nilgiris",
    "Karur",
    "Tiruchirappalli",
    "Perambalur",
    "Ariyalur",
    "Cuddalore",
    "Villupuram",
    "Kallakurichi",
    "Tiruvannamalai",
    "Kanyakumari",
    "Tirunelveli",
    "Thoothukudi",
    "Tenkasi",
    "Virudhunagar",
    "Madurai",
    "Theni",
    "Dindigul",
    "Sivaganga",
    "Ramanathapuram",
    "Mayiladuthurai",
    "Nagapattinam",
    "Tiruvarur",
    "Thanjavur",
    "Pudukkottai",
    "Chengalpattu",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Prayagraj",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kheri",
    "Kushi Nagar",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhotaudepur",
    "Dahod",
    "Dang",
    "Devbhumi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kheda",
    "Kutch",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada",
    "Navsari",
    "Panchmahal",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Tapi",
    "Vadodara",
    "Valsad",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Paschim Medinipur",
    "Purba Bardhaman",
    "Purba Medinipur",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur",
  ],
};

export function listDistrictsForState(state: IndiaState): string[] {
  const named = NAMED_DISTRICTS[state];
  const target = DISTRICT_COUNT_BY_STATE[state];
  if (named && named.length >= target) return named.slice(0, target).map(String);
  if (named && named.length < target) {
    const extra = target - named.length;
    const fill = Array.from({ length: extra }, (_, i) => `${state} Revenue Unit ${i + 1}`);
    return [...named, ...fill];
  }
  return Array.from({ length: target }, (_, i) => `${state} District ${i + 1}`);
}
